config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show, :update]
  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
    get 'collaborators/destroy'
  end
  resources :charges, only: [:new, :create]
  
  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end
  
  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

end

app/models/amount.rb
class Amount < ActiveRecord::Base
  def self.default
    return 15
  end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize { self.role ||= :standard }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  has_many :wikis
  has_many :collaborators
  has_many :wiki_collaborations, through: :collaborators, source: :wiki
  
  enum role: [:admin, :standard, :premium]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_many :collaborators
  has_many :users, through: :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Membership charge - #{current_user.email}",
      amount: Amount.default
    }
  end

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
    
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "Membership charge - #{current_user.email}",
      currency: 'usd'
    )
    
    if charge.paid
      flash[:notice] = "Thank you for your payment of #{charge.amount}, #{current_user.email}"
      current_user.premium!
      redirect_to wikis_path
    end
    
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def new
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find_by(email: params[:email])
    @collaborator = @wiki.collaborators.new(user: @user)

    if @user.nil?
      flash[:alert] = "There is no user by that email"
      redirect_to new_wiki_collaborator_path(@wiki)
    elsif @wiki.users.include?(@user)
      flash[:alert] = "There is already a collaborator by that email"
      redirect_to new_wiki_collaborator_path(@wiki)
    else
      if @collaborator.save
        flash[:notice] = "#{@user.email} has been added as a collaborator!"
      else
        flash[:alert] = "There was an error adding your collaborator"
      end
      redirect_to @wiki
    end
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.find(params[:id])
    
    if @collaborator.destroy
      flash[:notice] = "This user has been removed as a collaborator"
      redirect_to @wiki
    else
      flash[:alert] = "There was an error removing this user"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
  
  def update
    current_user.standard!
    current_user.wikis.update_all(private: false)
    redirect_to user_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = Wiki.all
    @wiki = Wiki.first || Wiki.find(params[:id])
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)
    
    unless current_user.admin? || current_user.premium?
      flash[:alert] = "You must be a premium subscriber to do that!"
      redirect_to @wiki && return
    end
    
    if @wiki.save
      redirect_to @wiki, notice: "Your wiki has been saved!"
    else
      flash[:alert] = "There was an error in saving your wiki!"
      render :new
    end
  end

  def new
    @wiki = Wiki.new
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @collaborators = @wiki.collaborators
  end

  def show
    @wikis = Wiki.all
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.update_attributes(wiki_params)
    collaborator = Collaborator.create(wiki_id: @wiki.id, user_id: current_user.id)
    @wiki.collaborators << collaborator
    
    if @wiki.save
      redirect_to @wiki
    else
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    
    if @wiki.destroy
      redirect_to action: :index
    else
      render :show
    end
  end
  
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
  
  def can_create_private_wiki?
    unless current_user.admin? || current_user.premium?
      flash.now[:alert] = "You must be a premium subscriber to do that!"
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Check out!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" 
    data-key="<%= @stripe_btn_data[:key] %>" 
    data-amount="<%= @stripe_btn_data[:amount] %>" 
    data-description="<%= @stripe_btn_data[:description] %>">
  </script>
<% end %>

app/views/collaborators/create.html.erb
<h1>Collaborators#create</h1>
<p>Find me in app/views/collaborators/create.html.erb</p>

app/views/collaborators/new.html.erb
</br>
<div class="row col-md-8 col-md-offset-2">
  <div class='form-group'>
    <%= form_tag [@wiki, @collaborator] do %>
    Find by email
    <%= email_field_tag :email %>
    <%= submit_tag "Add collaborator" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewRailsProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/showdown/1.6.4/showdown.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
 <% flash.each do |type, message| %>
   <div class="alert alert-<%= type %> fade in">
     <button class="close" data-dismiss="alert">x</button>
     <%= message %>
   </div>
 <% end %>
 <%= yield %>
</div>

</body>
</html>

app/views/users/show.html.erb
<div class='row'>
  <%= link_to "Home page", wikis_path %> | 
  <%= link_to "Sign out", destroy_user_session_path%>
</div>

<h1><%= @user.email %></h1>
<% if !current_user.admin? %>
  <% if current_user.standard? %>
    <h3><%= link_to "Upgrade to premium", new_charge_path %></h3>
  <% elsif current_user.premium? %>
    <h3><%= link_to "Switch me back to a normal subscription", user_path, method: :put, data: { confirm: 'Are you sure you would like to switch back to a normal subscription? Your private wikis will become public' } %></h3>
  <% end %>
<% end %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
  Signed in as: <strong><%= current_user.email %> - <%= link_to "Sign out", destroy_user_session_path, method: :delete %></strong>
<% else %>
  Welcome! <%= link_to "Sign up", new_user_registration_path %> - <%= link_to "Sign in", new_user_session_path %> 
<% end %>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |w| %>
  <div class='col-md-6'>
    <div class='form-group'>
      <%= w.label :title %>
      </br>
      <%= w.text_field :title, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= w.text_area :body, rows: 10, class: 'form-control' %>
    </div>
    <% if current_user.admin? || current_user.premium? %>
      <div class='form-group'>
        <%= w.label :private do %>
          <%= w.check_box :private, class: 'checkbox' %>
          <small>Make this wiki private</small>
        <% end %>
      </div>
    <% end %>
  <%= w.submit 'Save', class: 'btn btn-primary' %>
  <% if controller.action_name == 'edit' %>
    <% if current_user.id == @wiki.user_id || current_user.admin? %>
      <%= link_to 'Add a collaborator', new_wiki_collaborator_path(wiki_id: @wiki.id), class: 'btn btn-primary' %>
    <% end %>
  <% end %>
  <%= link_to 'cancel', @wiki, class: 'btn btn-danger' %>
<% end %>
</div>
<div class='col-md-6'>
  <h1>Preview</h1>
  <div id='markdown-preview'>

  </div>
</div>

app/views/wikis/_index.html.erb
<div class="col-md-4 pull-left index">
  <% @wikis.each do |wiki| %>
    <% if !current_user.standard? || !wiki.private? %>
    <div class="row col-md-12">
      <%= link_to wiki.title, wiki %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/wikis/edit.html.erb
<div class="row col-md-8 col-md-offset-2">
  <%= render 'form' %>
  <% if @collaborators %>
    <% @collaborators.each do |collaborator| %>
      <div>
        <span><%= collaborator.user.email %></span>
        <span><%= link_to 'Remove collaborator', wiki_collaborator_path(@wiki, collaborator), method: :delete %></span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/wikis/index.html.erb
<div class='page-nav user-link pull-right'>
  <%= link_to "My profile", user_path(current_user) %>
</div>
</br>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Wikis</h1>
    <% @wikis.each do |wiki| %>
      <% if !current_user.standard? || !wiki.private? %>
      <div class="row">
        <%= link_to wiki.title, wiki %>
      </div>
      <div class="row">
        <p><%= wiki.body %></p>
      </div>  
      <% end %>
    <% end %>
  </div>
</div>

app/views/wikis/new.html.erb
</br>
<div class="row col-md-8 col-md-offset-2">
  <%= render 'form' %>
</div>

app/views/wikis/show.html.erb
<div class='page-nav'>
  <%= link_to "Home page", wikis_path %> | 
  <%= link_to "Add a wiki", new_wiki_path %>
  <div class="user-links pull-right">
    <%= link_to "My profile", user_path(current_user) %>
  </div>
</div>
</br>
<div class="col-md-3 pull-left index">
  <% @wikis.each do |wiki| %>
    <% if !current_user.standard? || !wiki.private? %>
    <div class="row col-md-12">
      <%= link_to wiki.title, wiki %>
    </div>
    <% end %>
  <% end %>
</div>

<div class="col-md-9">
  <div class="row">
      <h3 class="media-body col-md-12">
        <%= @wiki.title %>
      </h3>
  </div>
  <div class="row col-md-12">
    <%= @wiki.body %>
  </div>
  
  <div class="row col-md-12">
    <%= link_to "Edit wiki", edit_wiki_path %>
    <%= link_to "Delete wiki", @wiki, method: :delete %>
  </div>
</div>